Switch to official minio image
The bitnami image seems to fail to create the buckets on
startup.

diff --git a/pipelines/pipelines-common/tests/docker-compose.yml b/pipelines/pipelines-common/tests/docker-compose.yml
--- a/pipelines/pipelines-common/tests/docker-compose.yml
+++ b/pipelines/pipelines-common/tests/docker-compose.yml
@@ -54,8 +54,8 @@ services:
         condition: service_completed_successfully
       lakekeeper-db:
         condition: service_healthy
-      minio:
-        condition: service_healthy
+      minio_createbucket:
+        condition: service_completed_successfully
     networks:
       - lakehouse_net
     ports:
@@ -93,25 +93,48 @@ services:
       - lakehouse_net
 
   minio:
-    image: bitnami/minio:latest
+    image: quay.io/minio/minio:latest
     environment:
-      - MINIO_ROOT_USER=minio-root-user
-      - MINIO_ROOT_PASSWORD=minio-root-password
-      - MINIO_API_PORT_NUMBER=9000
-      - MINIO_CONSOLE_PORT_NUMBER=9001
-      - MINIO_SCHEME=http
-      - MINIO_DEFAULT_BUCKETS=e2e-tests-warehouse
+      MINIO_ROOT_USER: minio-root-user
+      MINIO_ROOT_PASSWORD: minio-root-password
+      MINIO_API_PORT_NUMBER: 9000
+      MINIO_CONSOLE_PORT_NUMBER: 9001
+      MINIO_SCHEME: http
+    ports:
+      - 9001:9001
+      - 9000:9000
+    command: [ "server", "/data", "--console-address", ":9001" ]
     healthcheck:
-      test: ["CMD", "mc", "ls", "local", "|", "grep", "$$MINIO_DEFAULT_BUCKETS"]
-      interval: 2s
-      timeout: 10s
-      retries: 2
-      start_period: 15s
+      test: [ "CMD", "mc", "ready", "local" ]
+      interval: 30s
+      timeout: 20s
+      retries: 3
     networks:
       - lakehouse_net
-    ports:
-      - "9000:9000"
-      - "9001:9001"
+
+  minio_createbucket:
+    depends_on:
+      minio:
+        condition: service_healthy
+    image: quay.io/minio/mc:latest
+    environment:
+      MINIO_ROOT_USER: minio-root-user
+      MINIO_ROOT_PASSWORD: minio-root-password
+      MINIO_BUCKET_NAME: e2e-tests-warehouse
+    entrypoint: |
+      /bin/sh -c "
+      /usr/bin/mc alias set minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} \
+      if ! /usr/bin/mc ls minio/$${MINIO_BUCKET_NAME}; then \
+        echo \"Bucket '$${MINIO_BUCKET_NAME}' not found, creating...\" \
+        /usr/bin/mc mb minio/$${MINIO_BUCKET_NAME}; \
+        /usr/bin/mc anonymous set public minio/$${MINIO_BUCKET_NAME}; \
+        echo \"Bucket '$${MINIO_BUCKET_NAME}' created with public access policy\" \
+      else \
+        echo \"Found bucket '$${MINIO_BUCKET_NAME}'\" \
+      fi \
+      "
+    networks:
+      - lakehouse_net
 
   python-uv:
     profiles:
